/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;

import java.io.FileWriter;
import java.io.IOException;
import General.VentanaLogin;

/**
 *
 * @author Andres
 */
public class VentanaRegistroClienteAndres extends javax.swing.JFrame {
    
    /**
     * Creates new form ventanaRegistro
     */
    public VentanaRegistroClienteAndres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usuarioField = new javax.swing.JTextField();
        contrasenaField = new javax.swing.JTextField();
        nombreCompletoField = new javax.swing.JTextField();
        edadField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        registraseBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        administradorCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 280, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/city-abstract-photography-pq.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1100, 70));

        usuarioField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        usuarioField.setText("Ingrese su nombre de usuario");
        usuarioField.setBorder(null);
        usuarioField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioFieldMousePressed(evt);
            }
        });
        usuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioFieldActionPerformed(evt);
            }
        });
        jPanel1.add(usuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 380, -1));

        contrasenaField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        contrasenaField.setText("Ingrese su contraseña");
        contrasenaField.setBorder(null);
        contrasenaField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasenaFieldMousePressed(evt);
            }
        });
        contrasenaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaFieldActionPerformed(evt);
            }
        });
        jPanel1.add(contrasenaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 380, -1));

        nombreCompletoField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombreCompletoField.setText("Ingrese su nombre completo");
        nombreCompletoField.setBorder(null);
        nombreCompletoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreCompletoFieldMousePressed(evt);
            }
        });
        nombreCompletoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCompletoFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nombreCompletoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 380, -1));

        edadField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        edadField.setText("Ingrese su edad");
        edadField.setBorder(null);
        edadField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                edadFieldMousePressed(evt);
            }
        });
        edadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadFieldActionPerformed(evt);
            }
        });
        jPanel1.add(edadField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 380, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 330, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 330, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 330, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 330, 30));

        registraseBoton.setBackground(new java.awt.Color(153, 153, 153));
        registraseBoton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registraseBoton.setForeground(new java.awt.Color(255, 255, 255));
        registraseBoton.setText(" Registrarse");
        registraseBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraseBotonActionPerformed(evt);
            }
        });
        jPanel1.add(registraseBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 190, 70));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Britannic Bold", 1, 48)); // NOI18N
        jLabel4.setText("Registro");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 200, 60));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Edad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 70, 60));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText(" Nombre de usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 280, 60));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Nombre completo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 280, 60));

        administradorCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        administradorCheckBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        administradorCheckBox.setText("Administrador");
        administradorCheckBox.setActionCommand(" Administrador");
        administradorCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administradorCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(administradorCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioFieldMousePressed
        // TODO add your handling code here:
        
        usuarioField.setText("");
        
    }//GEN-LAST:event_usuarioFieldMousePressed

    private void usuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_usuarioFieldActionPerformed

    private void contrasenaFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaFieldMousePressed
        // TODO add your handling code here:
        
        contrasenaField.setText("");
        
    }//GEN-LAST:event_contrasenaFieldMousePressed

    private void contrasenaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaFieldActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_contrasenaFieldActionPerformed

    private void nombreCompletoFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreCompletoFieldMousePressed
        // TODO add your handling code here:
       
        nombreCompletoField.setText("");
        
    }//GEN-LAST:event_nombreCompletoFieldMousePressed

    private void nombreCompletoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCompletoFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nombreCompletoFieldActionPerformed

    private void edadFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edadFieldMousePressed
        // TODO add your handling code here:
        
        edadField.setText("");
        
    }//GEN-LAST:event_edadFieldMousePressed

    private void edadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_edadFieldActionPerformed

    private void registraseBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraseBotonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_registraseBotonActionPerformed

    private void administradorCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administradorCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_administradorCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroClienteAndres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroClienteAndres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroClienteAndres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroClienteAndres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroClienteAndres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox administradorCheckBox;
    private javax.swing.JTextField contrasenaField;
    private javax.swing.JTextField edadField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField nombreCompletoField;
    private javax.swing.JButton registraseBoton;
    private javax.swing.JTextField usuarioField;
    // End of variables declaration//GEN-END:variables
}
